spring:
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:properties/eureka-server.yml
      - classpath:properties/server.yml
  application:
    name: eureka-server
  profiles:
    active: local